name: Update Netease Music Box

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Build
        run: go build -o netease-music-box-go ./cmd/main.go
      - name: Run
        env:
          USER_ID: ${{ secrets.USER_ID }}
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          MARKDOWN_FILE: README.md
        run: ./netease-music-box-go
      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "update: netease music box" || echo "No changes to commit"
          git push
